using System;
using System.Collections.Generic;
using System.Windows;

namespace VictusLounge;

public partial class MainWindow
{
    private static readonly DependencyProperty LocalizationKeyProperty =
        DependencyProperty.RegisterAttached("LocalizationKey", typeof(string), typeof(MainWindow));

    private static readonly Dictionary<string, string> LocalizedTextKeys = new(StringComparer.Ordinal)
    {
        ["VictusLounge Control Center"] = "Common.AppTitle",
        ["VictusLounge"] = "Brand.Name",
        ["Gaming lounge workspace"] = "Brand.Subtitle",
        ["Рабочее пространство клуба"] = "Brand.Subtitle",
        ["Поиск: клиент, PC-04, бронь, турнир, платеж..."] = "Common.SearchPlaceholder",
        ["Выйти"] = "Common.Logout",

        ["Главная"] = "Nav.Dashboard",
        ["Схема клуба"] = "Nav.Map",
        ["Бронирование"] = "Nav.Booking",
        ["Кабинет"] = "Nav.Cabinet",
        ["Баланс"] = "Nav.Balance",
        ["События"] = "Nav.Events",
        ["Админ"] = "Nav.Admin",
        ["Смена"] = "Nav.Shift",
        ["Владелец"] = "Nav.Owner",
        ["Настройки"] = "Nav.Settings",

        ["ГОСТЕВОЙ ДОСТУП"] = "Auth.GuestAccess",
        ["Все для визита в клуб в одном профиле"] = "Auth.ClientPanelTitle",
        ["Бронируйте ПК, следите за балансом, получайте бонусы и возвращайтесь к любимым зонам без лишних звонков администратору."] = "Auth.ClientPanelText",
        ["Фрейм для фото клуба"] = "Auth.PhotoFrame",
        ["Сюда можно добавить фото игровой зоны, ресепшена или VIP-комнаты."] = "Auth.PhotoFrameHint",
        ["ВХОД ДЛЯ ГОСТЯ"] = "Auth.LoginKicker",
        ["Вернитесь в VictusLounge"] = "Auth.LoginHeading",
        ["Войдите, чтобы продолжить бронь, проверить баланс и увидеть ближайшие события клуба."] = "Auth.LoginSubtitle",
        ["Логин или email"] = "Auth.LoginField",
        ["Пароль"] = "Auth.Password",
        ["Войти"] = "Auth.SignIn",
        ["Создать аккаунт"] = "Auth.CreateAccount",
        ["НОВЫЙ ПРОФИЛЬ"] = "Auth.RegisterKicker",
        ["Создайте профиль гостя"] = "Auth.RegisterHeading",
        ["Сохраним ваши брони, бонусы и любимые зоны, чтобы следующий визит занимал меньше времени."] = "Auth.RegisterSubtitle",
        ["Имя"] = "Auth.Name",
        ["Логин"] = "Auth.Username",
        ["Создать и войти"] = "Auth.CreateAndEnter",
        ["Уже есть аккаунт"] = "Auth.AlreadyHaveAccount",
        ["ПРОФИЛЬ ГОСТЯ"] = "Auth.ProfileKicker",
        ["После регистрации сервис запомнит ваши предпочтения"] = "Auth.ProfilePanelTitle",
        ["Кабинет поможет быстрее бронировать места, видеть бонусы и получать приглашения на турниры и LAN-вечера."] = "Auth.ProfilePanelText",
        ["Фрейм для промо-фото"] = "Auth.PromoPhotoFrame",
        ["Добавьте сюда изображение клуба, команды или зоны, которую хотите показать новым гостям."] = "Auth.PromoPhotoFrameHint",
        ["Быстрая бронь"] = "Auth.FastBooking",
        ["Выбирайте дату, зону и ПК заранее"] = "Auth.FastBookingText",
        ["Личный баланс"] = "Auth.PersonalBalance",
        ["Пакеты времени, бонусы и история операций"] = "Auth.PersonalBalanceText",
        ["Любимые зоны"] = "Auth.FavoriteZones",
        ["Standard, VIP, Bootcamp или Royal"] = "Auth.FavoriteZonesText",
        ["События клуба"] = "Auth.ClubEvents",
        ["Турниры, командные брони и LAN-вечера"] = "Auth.ClubEventsText",

        ["CLUB STATUS"] = "Dashboard.Kicker",
        ["Рабочая панель клуба"] = "Dashboard.Title",
        ["Состояние зала, броней и смены на сегодня."] = "Dashboard.Subtitle",
        ["Новая бронь"] = "Common.NewBooking",
        ["Схема"] = "Common.ClubMapShort",
        ["Свободно ПК"] = "Dashboard.FreePc",
        ["из 56"] = "Dashboard.OutOf56",
        ["Активные брони"] = "Dashboard.ActiveBookings",
        ["5 ожидают оплату"] = "Dashboard.PaymentWaiting",
        ["Активные сессии"] = "Dashboard.ActiveSessions",
        ["3 заканчиваются скоро"] = "Dashboard.EndingSoon",
        ["События сегодня"] = "Dashboard.TodayEvents",
        ["QUICK ACTIONS"] = "Common.QuickActions",
        ["Быстрые действия"] = "Common.QuickActions",
        ["Записаться на турнир"] = "Dashboard.JoinTournament",
        ["Купить пакет"] = "Dashboard.BuyPackage",
        ["Открыть профиль"] = "Dashboard.OpenProfile",
        ["Дата, зона, ПК, summary"] = "Dashboard.BookingHint",
        ["Dota 2, CS2, LAN Party"] = "Dashboard.TournamentHint",
        ["Quick Game / Night Pack"] = "Dashboard.PackageHint",
        ["Бонусы, сессии, брони"] = "Dashboard.ProfileHint",
        ["Сегодня в клубе"] = "Dashboard.TodayClub",
        ["Зоны клуба"] = "Dashboard.Zones",
        ["Последние уведомления"] = "Dashboard.LastNotifications",

        ["CLUB MAP"] = "Map.Kicker",
        ["Интерактивная схема клуба"] = "Map.Title",
        ["Зоны клуба, статусы ПК и ближайшие свободные интервалы видны без перехода в таблицы."] = "Map.Subtitle",
        ["ресепшен / турникет"] = "Map.EntranceSub",
        ["касса и старт сессий"] = "Map.AdminSub",
        ["склад / техника"] = "Map.ServiceSub",
        ["PC DETAIL"] = "Map.PcDetail",
        ["Выберите ПК"] = "Map.SelectPc",
        ["После выбора здесь появятся зона, статус, железо, тариф и ближайшие свободные интервалы."] = "Map.DetailPlaceholder",
        ["Фото места"] = "Map.PhotoPlace",
        ["Заглушка до загрузки реальных фото"] = "Map.PhotoPlaceholder",
        ["Свободные интервалы появятся после выбора места."] = "Map.FreeIntervals",
        ["Забронировать выбранный ПК"] = "Map.BookSelected",
        ["ПК недоступен для брони"] = "Map.PcUnavailable",

        ["BOOKING FLOW"] = "Booking.Kicker",
        ["Выберите дату, зону, один или несколько ПК, затем проверьте итог перед подтверждением."] = "Booking.Subtitle",
        ["Одиночная"] = "Booking.Single",
        ["Для компании"] = "Booking.Company",
        ["Зона"] = "Booking.Zone",
        ["Тариф"] = "Booking.Tariff",
        ["Начало"] = "Booking.Start",
        ["Выбор ПК"] = "Booking.SelectPc",
        ["SUMMARY"] = "Booking.Summary",
        ["Итог брони"] = "Booking.SummaryTitle",
        ["ПК"] = "Booking.Pc",
        ["Дата"] = "Booking.Date",
        ["Время"] = "Booking.Time",
        ["Длительность"] = "Booking.Duration",
        ["Без скидки"] = "Booking.BaseTotal",
        ["Скидка"] = "Booking.Discount",
        ["Итого"] = "Booking.Total",
        ["Подтвердить бронь"] = "Booking.Confirm",
        ["Очистить выбор"] = "Booking.Clear",
        ["1 час"] = "Booking.OneHour",
        ["2 часа"] = "Booking.TwoHours",
        ["3 часа"] = "Booking.ThreeHours",
        ["Часы"] = "Booking.Hours",
        ["Минуты"] = "Booking.Minutes",

        ["CLIENT PROFILE"] = "Cabinet.Kicker",
        ["Личный кабинет"] = "Cabinet.Title",
        ["Профиль игрока, лояльность, активные брони, сессии и быстрые действия."] = "Cabinet.Subtitle",
        ["Забронировать ПК"] = "Common.BookPc",
        ["Прогресс до Elite"] = "Cabinet.Progress",
        ["72% · осталось 420 бонусных очков"] = "Cabinet.ProgressValue",
        ["Активная бронь"] = "Cabinet.ActiveBooking",
        ["Следующая выгода"] = "Cabinet.NextBenefit",
        ["Подсказка обновляется по текущим тарифам."] = "Cabinet.NextBenefitText",
        ["Получено бонусов"] = "Cabinet.Bonuses",
        ["Наиграно"] = "Cabinet.Played",
        ["Любимая зона"] = "Cabinet.FavoriteZone",
        ["Пополнить баланс"] = "Cabinet.Topup",
        ["Текущая сессия"] = "Cabinet.LastSessions",
        ["Сумма"] = "Table.Amount",

        ["SETTINGS"] = "Nav.Settings",
        ["Смена темы приложения и языка интерфейса."] = "Settings.Subtitle",
        ["Тема приложения"] = "Settings.ThemeTitle",
        ["Black Gold оставляет премиальный стиль клуба, Graphite дает более холодный рабочий вид."] = "Settings.ThemeDescription",
        ["Язык интерфейса"] = "Settings.LanguageTitle",
        ["Переключает основные элементы навигации и страницу настроек."] = "Settings.LanguageDescription"
    };
}
